=== raulfdezesc/ocap/src/main/webapp/WEB-INF/config/ConfigurationRepository.xsd
<?xml version="1.0" encoding="iso-8859-1" standalone="yes"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<!-- Nodo raíz -->
	<xsd:element name="configurations">
		<xsd:complexType>
			<xsd:sequence>
				<!-- propiedades globales -->
				<xsd:element ref="globals" />
				<xsd:element ref="contexts" />
			</xsd:sequence>
			<xsd:attribute name="version" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<!-- Propiedades Globales -->
	<xsd:element name="globals">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="initialPath">
					<xsd:complexType>
						<xsd:complexContent>
							<xsd:restriction base="xsd:anyType">
								<xsd:attribute name="value" use="required" type="xsd:string" />
							</xsd:restriction>
						</xsd:complexContent>
					</xsd:complexType>
				</xsd:element>
				<xsd:element ref="properties" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<!-- Lista de Propiedades -->
	<xsd:element name="properties">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="property" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<!-- Una Propiedad -->
	<xsd:element name="property">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:restriction base="xsd:anyType">
					<xsd:attribute name="name" use="required" type="xsd:string" />
					<xsd:attribute name="value" use="required" type="xsd:int" />
					<xsd:attribute name="comment" use="required" type="xsd:string" />
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>

	<!-- Lista de Contextos -->
	<xsd:element name="contexts">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="context" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<!-- Un Contexto -->
	<xsd:element name="context">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="configurationFile" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="id" use="required" type="xsd:string" />
			<xsd:attribute name="name" use="required" type="xsd:string" />
			<xsd:attribute name="minimumCheckDelay" type="xsd:int" />
			<xsd:attribute name="contextTimeOut" type="xsd:int" />
		</xsd:complexType>
	</xsd:element>

	<!-- Un Fichero de Configuración -->
	<xsd:element name="configurationFile">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:restriction base="xsd:anyType">
					<xsd:attribute name="id" use="required" type="xsd:string" />
					<xsd:attribute name="name" use="required" type="xsd:string" />
					<xsd:attribute name="location" use="required" type="xsd:string" />
					<xsd:attribute name="minimumCheckDelay" use="optional"
						type="xsd:int" />
					<xsd:attribute name="comment" use="optional" type="xsd:string" />
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== raulfdezesc/ocap/src/main/webapp/WEB-INF/config/ConfigurationRepository.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<configurations version="1.0"
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:schemaLocation='ConfigurationRepository.xsd'>

	<!-- Configuraciones globales a todos los contextos -->
	<globals>
		<!-- Ruta base para todos los ficheros de configuración -->
		<initialPath value="${web-inf.directory}/config/" />

		<!-- Propiedades globales -->
		<properties>
			<property name="minimumCheckDelay" value="300000"
				comment="Tiempo de recarga de las propiedades de configuración (un valor de 0 equivale a no recargar). Expresado en milisegundos." />
			<property name="contextTimeOut" value="300000"
				comment="Tiempo que el sistema mantiene el contexto en memoria (un valor de 0 equivale a no recargar). Expresado en milisegundos." />
		</properties>
	</globals>

	<!-- Lista de contextos de la aplicación -->
	<contexts>
		<context id="default" name="Configuración de la aplicación"
			minimumCheckDelay="300000" contextTimeOut="900000">
			<configurationFile id="1" name="AppConfig"
				location="./app-config.properties" minimumCheckDelay="300000"
				comment="" />
		</context>
		<context id="log" name="Configuración Sistema Log"
			minimumCheckDelay="300000" contextTimeOut="300000">
			<configurationFile id="ficheroLog4j" name="LogConfig"
				location="./log.xml" minimumCheckDelay="300000" comment="" />
		</context>
	</contexts>
</configurations>
